### ISSUE TITLE
The from_unixtime function does not correctly determine the field data type when CREATE MATERIALIZED VIEW

### ISSUE THREAD

**Issue by syyfffy** [StarRocks/starrocks#15285] opened 2022-12-15 08:56 UTC
### Steps to reproduce the behavior (Required)
1. CREATE MATERIALIZED VIEW std_123
DISTRIBUTED BY HASH(`corpId`,`empId`) BUCKETS 8
REFRESH ASYNC START('2022-11-22 10:30:20') EVERY (interval 5 second) as
select 
	cast(table_data -> 'corpId' as string) corpId,
	cast(table_data -> 'empId' as string)  empId,
    from_unixtime(cast(table_data -> 'effectDate_$date'  as bigint)/1000)  effectDate_$date,  
    cast(table_data -> 'effectVersion' as string)  effectVersion,
    table_data,
    time
from ods_mongdb_data_source 
where table_name ='venus_hrm_employee_history'
and cast(table_data->'delete' as string)='normal' ;

2. SELECT *  from std_123;

### Expected behavior (Required)
// 这里没有任何数据，本身select是有数据的，创建物化视图没有数据
SELECT * FROM INFORMATION_SCHEMA.task_runs;
   ERROR_CODE = -1；
   ERROR_MESSAGE = 'com.starrocks.sql.common.DmlException: 172.16.0.243: string length(19) > limit(3), string: 1980-01-01 00:00:001980-01-01 00:00:002022-11-09 00:00:002022-11-09 00:00:002022-11-09 00:00.......一直循环如此'

desc std_123;

Field,Type,Null,Key,Default,Extra
"corpId","VARCHAR(65533)","Yes","true",null,""
"empId","VARCHAR(65533)","Yes","false",null,"NONE"
"effectDate_$date","VARCHAR","Yes","false",null,"NONE"
"effectVersion","VARCHAR(65533)","Yes","false",null,"NONE"
"table_data","JSON","Yes","false",null,"NONE"
"time","DATETIME","Yes","false",null,"NONE"

effectDate_$date 字段给了VARCHAR类型，但是我们使用的是from_unixtime函数，应该是datetime类型

### Real behavior (Required)
不创建物化视图进行select 查询结果有数据，

**Comment by Astralidea** [comment] 2022-12-19 03:02
This problem is caused by wrong type inference of materialized views, which has been fixed in version 2.4.1 and later. #12796
The inference of type VARCHAR is reasonable. Because the following example:
```
mysql> select from_unixtime(0, '%Y');
+------------------------+
| from_unixtime(0, '%Y')  |
+------------------------+
| 1970                                 |
+------------------------+
```
If you want to use datetime type, you can try to display conversion, for example:
```
CREATE MATERIALIZED VIEW std_123
    -> DISTRIBUTED BY HASH(test) BUCKETS 8
    -> REFRESH ASYNC START('2022-12-20 10:30:20') EVERY (interval 5 second) as
    -> select
    -> cast(from_unixtime(cast(k1 as bigint)/1000) as datetime) test
    -> from t2
    -> ;
```

**Closed by Astralidea** 2022-12-19 03:02 UTC
Labels: type/bug
