### ISSUE TITLE
Hive external table does not support array data type

### ISSUE THREAD

**Issue by tiannan-sr** [StarRocks/starrocks#1190] opened 2021-11-10 13:04 UTC
### Steps to reproduce the behavior (Required)
1. create hive table which contains array data type:
create table hive_hdfs_orc_nocompress(
 col_tinyint tinyint comment "column tinyint"
,col_smallint smallint comment "column smallint"
,col_int int comment "column int"
,col_integer integer comment "column integer"
,col_bigint bigint comment "column bigint"
,col_float float comment "column float"
,col_double double comment "column double"
,col_double_precision double precision comment "column double precision"
,col_decimal decimal(10,2) comment "column decimal"
,col_timestamp timestamp comment "column timestamp"
,col_date date comment "column date"
,col_string string comment "column string"
,col_varchar varchar(100) comment "column varchar"
,col_binary binary comment "column binary"
,col_char char(100) comment "column char"
,col_boolean boolean comment "column boolean"
,col_array array<int> comment "column array"
)
clustered by(col_int) sorted by(col_int) into 32 buckets
row format delimited fields terminated by ','
collection items terminated by '_'
stored as orc
tblproperties("orc.compress"="none");

2.create hive external table:
CREATE external TABLE array_test (
 col_int int,
 col_array array<int>
) ENGINE=hive         
properties (             
"resource" = "hive_resource_stability",             
"table" = "hive_hdfs_orc_nocompress",             
"database" = "tn_test"); 

### Expected behavior (Required)
hive external table support array data type, and the hive external table which contains array data type can create successfully.

### Real behavior (Required)
the hive external table which contains array data type create failed:
ERROR 1064 (HY000): can not convert hive column type [array<int>] to starrocks type [INVALID_TYPE]

### StarRocks version (Required)
 2.0
mysql> select current_version();
+-------------------+
| current_version() |
+-------------------+
| UNKNOWN cfd8fc1   |
+-------------------+
1 row in set (0.01 sec)

**Comment by imay** [comment] 2021-11-11 06:19
I think this is not a bug. This should be a new feature.
I will change its type.

**Comment by caneGuy** [comment] 2021-11-26 03:05
i would like to finish this feature. who can i discuss with? @imay @gengjun-git

**Comment by imay** [comment] 2021-11-26 03:22
> 

@caneGuy 
Great, I will assign this issue to you.

You should implement for each format, such as Parquet and ORC.
IMO, it is easier to implement array type in ORC format, because ORC's array format is the same with StarRocks'.
It is a little difficult to implement Parquet Array. If you want to implement parquet array, you should known parquet's format very well.

**Comment by caneGuy** [comment] 2021-11-26 06:48
@imay that's make sense, i will post a POC recently

**Comment by caneGuy** [comment] 2022-01-10 10:57
please assign to @DorianZheng

**Comment by DorianZheng** [comment] 2022-02-18 07:02
https://github.com/StarRocks/starrocks/pull/2946

**Closed** 2022-04-11 09:34 UTC
Labels: type/enhancement
