### ISSUE TITLE
Paimon connector error

### ISSUE THREAD

**Issue by Aload** [StarRocks/starrocks#30930] opened 2023-09-13 02:14 UTC
### Steps to reproduce the behavior (Required)
1.
CREATE EXTERNAL CATALOG paimon_catalog_fs
PROPERTIES
(
    "type" = "paimon",
    "paimon.catalog.type" = "filesystem",
    "paimon.catalog.warehouse" = "s3://paimon/namespace",
    "aws.s3.enable_ssl" = "false",
    "aws.s3.enable_path_style_access" = "true",
    "aws.s3.endpoint" = "http://10.0.9.76:9199",
    "aws.s3.access_key" = "admin",
    "aws.s3.secret_key" = "Dpjg40uIJr"
);

CREATE DATABASE test_water_platform;

#DROP Catalog paimon_catalog_fs;

SHOW CATALOGS;
SHOW CREATE CATALOG paimon_catalog_fs;
SHOW DATABASES FROM paimon_catalog_fs;
SET CATALOG  paimon_catalog_fs;
SHOW DATABASES;
USE  ods;
CREATE TABLE IF NOT EXISTS `tax_catalog`.ods.ods_bn_fee_info_zg(
fee_id	BIGINT,
fee_date	BIGINT,
fee_state	STRING,
fee_state_desc	STRING,
fee_type	STRING,
fee_type_name	STRING,
cancel_debt_date	BIGINT,
cancel_debt_mode	STRING,
cancel_debt_mode_desc	STRING,
write_off_batch	BIGINT,
amount_received	DOUBLE,
amount	DOUBLE,
settle_mode	STRING,
settle_mode_desc	STRING,
settle_date	BIGINT,
reckoner	BIGINT,
cancel_debt_clerk	BIGINT,
previous_balance	DOUBLE,
current_balance	DOUBLE,
user_name	STRING,
user_no	BIGINT,
address	STRING,
user_type	BIGINT,
meter_no	STRING,
account_type	STRING,
account_type_desc	STRING,
account_no	BIGINT,
water_bill_id	BIGINT,
update_date	BIGINT,
region_code	BIGINT,
caliber	BIGINT,
fee_code	STRING,
read_time	STRING,
tenant_id	BIGINT)PARTITIONED BY (tenant_id,read_time) WITH (
'bucket'  =  '12',
'scan.manifest.parallelism'  =  '10',
'write-mode'  =  'append-only',
'sink.parallelism'  =  '12',
'file.format'  =  'parquet')
2. INSERT INTO '....'
3. select * from xxx limit 10

### Expected behavior (Required)
Normal Query

### Real behavior (Required)
org.jkiss.dbeaver.model.sql.DBSQLException: SQL 错误 [1064] [42000]: Failed to call the nextChunkOffHeap method of off-heap table scanner. java exception details: java.io.IOException: Failed to get the next off-heap table chunk of paimon.[com.starrocks.paimon.reader.PaimonSplitScanner.getNext(PaimonSplitScanner.java:211), com.starrocks.jni.connector.ConnectorScanner.getNextOffHeapChunk(ConnectorScanner.java:101)]
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:133)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeStatement(SQLQueryJob.java:582)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.lambda$1(SQLQueryJob.java:491)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:189)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:498)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.extractData(SQLQueryJob.java:934)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:3919)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:123)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:189)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:121)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer$ResultSetDataPumpJob.run(ResultSetViewer.java:5101)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.sql.SQLSyntaxErrorException: Failed to call the nextChunkOffHeap method of off-heap table scanner. java exception details: java.io.IOException: Failed to get the next off-heap table chunk of paimon.[com.starrocks.paimon.reader.PaimonSplitScanner.getNext(PaimonSplitScanner.java:211), com.starrocks.jni.connector.ConnectorScanner.getNextOffHeapChunk(ConnectorScanner.java:101)]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
	at com.mysql.cj.jdbc.StatementImpl.executeInternal(StatementImpl.java:764)
	at com.mysql.cj.jdbc.StatementImpl.execute(StatementImpl.java:648)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.execute(JDBCStatementImpl.java:330)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:131)
### StarRocks version (Required)
 - 3.1.2

**Comment by 0akarma** [comment] 2023-09-13 12:35
3.1.2 docker image maybe not include the latest bugfix in branch `main`
![image](https://github.com/StarRocks/starrocks/assets/31059713/74d404e6-a46d-45f0-915f-620a65775fc9)

**Comment by Aload** [comment] 2023-09-14 06:54
> The version of `3.1.2` image maybe not including the latest bugfix of some special type adaption in branch `main`
> You can have a try in branch `main` and it works good to me.
There is a part of the table can be queried normally, but some table queries have corresponding problems. On Dingding, I have given feedback and consulted mr Wuqian, which has not been solved for the time being

**Comment by Xiangakun** [comment] 2023-10-11 07:59
Any progress for this, Please? I have met the same problem when using version of 3.1.2

**Comment by Aload** [comment] 2023-10-11 08:47
> Any progress for this, Please? I have met the same problem when using version of 3.1.2

No one's paying attention for a while

**Comment by Xiangakun** [comment] 2023-11-01 06:03
I find out the root cause of the problem, the error threw because the type of the index of target InternalRow is not the same as the input `logicalTypes[i]`, the error should only happen when use `select *` or select all the column from paimon table. And it's caused by following code in `PaimonSplitScanner`, I think we can remove the if condition directly to fix the problem, I test query like `select * from paimon_table` works fine after the fix. However, I don't do the full test yet.
<img width="1305" alt="image" src="https://github.com/StarRocks/starrocks/assets/20922357/238c3039-f5e5-41ca-8d94-a1800107f85f">

**Comment by Aload** [comment] 2023-11-01 10:22
> fee_id

![image](https://github.com/StarRocks/starrocks/assets/13082598/c2bfee7b-5c0a-4fb5-a78b-cd487da90e85)
Referring to your experiment, I tried to query only one field, but this problem still occurs

**Comment by Xiangakun** [comment] 2023-11-01 10:45
> > fee_id
> 
> ![image](https://user-images.githubusercontent.com/13082598/279646633-c2bfee7b-5c0a-4fb5-a78b-cd487da90e85.png) Referring to your experiment, I tried to query only one field, but this problem still occurs

This error is different from the issue we talked about above, it happened when method `open` was called, instead of `getNext ` being called. You can refer to `jni.INFO.log` under be/log/ folder to get more details

**Comment by miomiocat** [comment] 2023-12-05 07:33
fixed by https://github.com/StarRocks/starrocks/pull/35774

**Closed by miomiocat** 2023-12-05 07:33 UTC
Labels: type/bug
