### ISSUE TITLE
Can not create table when one BE is decommissioned

### ISSUE THREAD

**Issue by Youngwb** [StarRocks/starrocks#6145] opened 2022-05-16 08:39 UTC
### Steps to reproduce the behavior (Required)
![image](https://user-images.githubusercontent.com/9495145/168552418-14066bf1-6c01-402e-b2ec-6eda5136b1d5.png)

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`

**Comment by nshangyiming** [comment] 2022-08-02 05:10
cannot reproduce on main branch, going to close this issue,

![image](https://user-images.githubusercontent.com/107105845/182296403-7eab24f6-1296-492c-b214-86652e37554e.png)

```
CREATE TABLE IF NOT EXISTS t0 ( c_0_0 DATE NULL, c_0_1 SMALLINT NOT NULL, c_0_2 ARRAY<INT> NULL, c_0_3 DECIMAL(22, 14) NOT NULL, c_0_4 DECIMAL(25, 12) NULL, c_0_5 VARCHAR(31) NULL, INDEX index1_c_0_0(`c_0_0`) USING BITMAP) UNIQUE KEY(c_0_0, c_0_1) PARTITION BY RANGE (c_0_0) (START  ("2010-01-01") END  ("2021-12-31") EVERY  (INTERVAL 132 day)) DISTRIBUTED BY HASH (c_0_1) BUCKETS 3 properties ("replication_num"="1");
```

**Comment by nshangyiming** [comment] 2022-08-02 05:12
should be noticed, the two BEs are on same host, will try to reproduce in that case

**Closed** 2022-08-06 09:20 UTC
Labels: type/bug
