### ISSUE TITLE
Hive external table query failed: Type mismatch: orc VARCHAR(100) to native CHAR(100)

### ISSUE THREAD

**Issue by gengjun-git** [StarRocks/starrocks#1199] opened 2021-11-11 04:53 UTC
### Steps to reproduce the behavior (Required)
create table in hive
```sql
create table hive_table_test.hive_hdfs_orc_nocompress(
 col_tinyint tinyint comment "column tinyint"
,col_smallint smallint comment "column smallint"
,col_int int comment "column int"
,col_integer integer comment "column integer"
,col_bigint bigint comment "column bigint"
,col_float float comment "column float"
,col_double double comment "column double"
,col_double_precision double precision comment "column double precision"
,col_decimal decimal comment "column decimal"
,col_timestamp timestamp comment "column timestamp"
,col_date date comment "column date"
,col_string string comment "column string"
,col_varchar varchar(100) comment "column varchar"
,col_binary binary comment "column binary"
,col_char char(100) comment "column char"
,col_boolean boolean comment "column boolean"
)
clustered by(col_int) sorted by(col_int) into 32 buckets
row format delimited fields terminated by ','
stored as orc
tblproperties("orc.compress"="none");

insert into hive_table_test.hive_hdfs_orc_nocompress values
 (1,1,1,1,1,1.001,10.1,110.1,1110.1,'2021-10-30 12:10:23','2021-10-30','hello world','hi','1110001010101011001001','nihao',true);
```

create external table in starrocks
```sql
create external resource hive_resource_1635837105500 PROPERTIES("type" = "hive","hive.metastore.uris" = "thrift://172.26.92.141:9083");
create external table ex_hive_tbl (                 
 col_tinyint tinyint comment "column tinyint"                 ,
 col_smallint smallint comment "column smallint"                 ,
 col_int int comment "column int"                 ,
 col_integer integer comment "column integer"                 ,
 col_bigint bigint comment "column bigint"                 ,
 col_float float comment "column float"                 ,
 col_double double comment "column double"                 ,
 col_double_precision double comment "column double precision"                 ,
 col_decimal decimal comment "column decimal"                 ,
 col_timestamp datetime comment "column timestamp"                 ,
 col_date date comment "column date"                 ,
 col_string varchar(1000) comment "column string"                 ,
 col_varchar varchar(100) comment "column varchar"                 ,
 col_binary varchar(1000) comment "column binary"                 ,
 col_char char(100) comment "column char"                 ,
 col_boolean boolean comment "column boolean"             )             
 ENGINE=hive             
 properties (                 
  "resource" = "hive_resource_1635837105500",                
   "table" = "hive_hdfs_orc_nocompress",                
    "database" = "hive_table_test");
```

execute query
```sql
mysql> select * from ex_hive_tbl;
ERROR 1064 (HY000): Type mismatch: orc VARCHAR(100) to native CHAR(100)
```

### StarRocks version (Required)
- 1.19

**Comment by caneGuy** [comment] 2021-11-11 06:08
i would like to solve this problem

**Comment by imay** [comment] 2021-11-11 06:22
@caneGuy Thank you.
I will assign this to you

**Comment by gengjun-git** [comment] 2021-11-11 06:27
Can discuss with @dirtysalt

**Comment by caneGuy** [comment] 2021-11-13 02:44
error log on be as below
```
W1113 10:40:08.429477  7698 plan_fragment_executor.cpp:227] fail to open fragment, instance_id=029a945a-442b-11ec-91e6-00163e36be45, status=Not supported: Type mismatch: orc VARCHAR(100) to native CHAR(100)
W1113 10:40:08.459759  7697 fragment_mgr.cpp:195] Fail to open fragment 029a945a-442b-11ec-91e6-00163e36be46: Cancelled: Cancelled SenderQueue::get_chunk
W1113 10:40:08.459764  7698 fragment_mgr.cpp:195] Fail to open fragment 029a945a-442b-11ec-91e6-00163e36be45: Not supported: Type mismatch: orc VARCHAR(100) to native CHAR(100)
```

**Comment by caneGuy** [comment] 2021-11-13 10:15
i tested in presto & impala, there is no such error. starrocks is caused by
```
const static std::unordered_map<orc::TypeKind, PrimitiveType> g_orc_starrocks_type_mapping = {
        {orc::BOOLEAN, TYPE_BOOLEAN}, {orc::BYTE, TYPE_TINYINT},
        {orc::SHORT, TYPE_SMALLINT},  {orc::INT, TYPE_INT},
        {orc::LONG, TYPE_BIGINT},     {orc::FLOAT, TYPE_FLOAT},
        {orc::DOUBLE, TYPE_DOUBLE},   {orc::DECIMAL, TYPE_DECIMALV2},
        {orc::DATE, TYPE_DATE},       {orc::TIMESTAMP, TYPE_DATETIME},
        {orc::STRING, TYPE_VARCHAR},  {orc::BINARY, TYPE_VARCHAR},
        {orc::CHAR, TYPE_VARCHAR},    {orc::VARCHAR, TYPE_VARCHAR},
};
```

**Comment by dirtysalt** [comment] 2021-11-13 14:01
@caneGuy @imay Could you check out this fixup https://github.com/StarRocks/starrocks/pull/1176

**Closed** 2021-11-17 05:11 UTC
Labels: type/bug, external/hive
