### ISSUE TITLE
[sqlancer] query unknow error

### ISSUE THREAD

**Issue by wanpengfei-git** [StarRocks/starrocks#9933] opened 2022-08-12 07:35 UTC
### Steps to reproduce the behavior (Required)
```
DROP DATABASE IF EXISTS n2;
CREATE DATABASE n2;
USE n2;
admin set frontend config ("enable_decimal_v3" = "true");
CREATE TABLE t0 (c_0_0 DATETIME NOT NULL ,c_0_1 VARCHAR(11) NULL ,c_0_2 DATETIME NOT NULL ,c_0_3 CHAR(11) NOT NULL ,c_0_4 BOOLEAN NULL ,c_0_5 TINYINT NULL ,c_0_6 DECIMAL(4, 1)  MIN NULL ,c_0_7 DATE REPLACE NOT NULL ,c_0_8 DATETIME REPLACE NOT NULL ,c_0_9 HLL HLL_UNION NOT NULL , INDEX index1_c_0_0(`c_0_0`) USING BITMAP) AGGREGATE KEY (c_0_0,c_0_1,c_0_2,c_0_3,c_0_4,c_0_5) PARTITION BY RANGE(c_0_0) (START ("2010-01-01") END ("2022-12-31") EVERY (INTERVAL 128 day)) DISTRIBUTED BY HASH (c_0_1,c_0_4,c_0_5) BUCKETS 3 properties("replication_num"="3") ;
CREATE TABLE t1 (c_1_0 DATETIME NOT NULL,c_1_1 VARCHAR(21) NOT NULL,c_1_2 DATETIME NOT NULL,c_1_3 DATE NOT NULL,c_1_4 TINYINT NOT NULL,c_1_5 BOOLEAN NOT NULL,c_1_6 BOOLEAN NOT NULL,c_1_7 DATETIME NOT NULL,c_1_8 SMALLINT NOT NULL,c_1_9 BOOLEAN NOT NULL,c_1_10 BIGINT NOT NULL,c_1_11 FLOAT NOT NULL,c_1_12 DATETIME NOT NULL,c_1_13 BOOLEAN NOT NULL,c_1_14 FLOAT NOT NULL,c_1_15 ARRAY<STRING> NOT NULL, INDEX index1_c_1_5(`c_1_5`) USING BITMAP) PRIMARY KEY (c_1_0,c_1_1,c_1_2,c_1_3,c_1_4,c_1_5,c_1_6,c_1_7,c_1_8,c_1_9,c_1_10) PARTITION BY RANGE(c_1_2) (START ("2010-01-01") END ("2022-12-31") EVERY (INTERVAL 131 day)) DISTRIBUTED BY HASH (c_1_4,c_1_10,c_1_3) BUCKETS 3 properties("replication_num"="3", "bloom_filter_columns"="c_1_8") ;
CREATE TABLE t2 (c_2_0 DATE NOT NULL,c_2_1 DATETIME NOT NULL,c_2_2 DATETIME NOT NULL,c_2_3 VARCHAR(1) NOT NULL,c_2_4 VARCHAR(1) NOT NULL,c_2_5 BOOLEAN NOT NULL,c_2_6 DATETIME NOT NULL,c_2_7 ARRAY<INT> NOT NULL,c_2_8 DECIMAL(5, 4)  NOT NULL,c_2_9 BOOLEAN NOT NULL,c_2_10 DECIMAL(20, 10)  NOT NULL,c_2_11 ARRAY<INT> NOT NULL) PRIMARY KEY (c_2_0,c_2_1,c_2_2,c_2_3,c_2_4,c_2_5,c_2_6) PARTITION BY RANGE(c_2_0) (START ("2010-01-01") END ("2022-12-31") EVERY (INTERVAL 249 day)) DISTRIBUTED BY HASH (c_2_3,c_2_5,c_2_1,c_2_4,c_2_6,c_2_0) BUCKETS 3 properties("replication_num"="3") ;
INSERT INTO t1 VALUES ('2010-01-09 08:00:14', 'lqB', '2010-01-21 08:00:14', '2010-01-01', 4, false, false, '2010-01-07 08:00:14', 2, false, 1276746506, 1.276746506E9, '2010-01-25 08:00:14', false, 0.9978663917836372, ["Flx", "iyrxnLa", "L", "m"]), ('2010-01-02 08:00:14', 'gwEJC', '2010-01-03 08:00:14', '2010-01-22', 3, false, false, '2010-01-18 08:00:14', 8, false, 256484637, 0.20105946131679264, '2010-01-20 08:00:14', true, 0.20105946131679264, ["treS", "5Y", "uR", "U", "Z1kriBHO", "", "v3BFm1eQ2", "", "", "S0X", "j"]);
INSERT INTO t1 VALUES ('2010-01-10 08:00:14', 'hF', '2010-01-04 08:00:14', '2010-01-13', 7, false, false, '2010-01-26 08:00:14', 2, false, 256484637, 0.2846639637069026, '2010-01-15 08:00:14', true, 0.28258588769101267, []), ('2010-01-19 08:00:14', '7qf', '2010-01-26 08:00:14', '2010-01-02', 1, true, true, '2010-01-07 08:00:14', 15, true, 438481840, 0.698973174640645, '2010-01-17 08:00:14', false, 0.10010067221895869, ["", "YQ", "UO", "Kc", "2lPv13", "1g", ""]);
TRUNCATE TABLE t0;
INSERT INTO t2 VALUES ('2010-01-19', '2010-01-22 08:00:14', '2010-01-12 08:00:14', '', '', false, '2010-01-08 08:00:14', [], 0.0008, false, 0.4042818889, [-294254550, -294254550, 643562450, -8297501, -772861656, 1276746506, -294254550, 1276746506]);
INSERT INTO t1 VALUES ('2010-01-01 08:00:14', 'W', '2010-01-12 08:00:14', '2010-01-11', 1, true, true, '2010-01-28 08:00:14', 3, true, -587660898, 0.5797383985295895, '2010-01-09 08:00:14', true, 0.6229592321560707, ["Zb", ""]), ('2010-01-29 08:00:14', 'NyGbaKiF', '2010-01-29 08:00:14', '2010-01-12', 6, false, false, '2010-01-29 08:00:14', 3, false, -896198980, -2.9425455E8, '2010-01-31 08:00:14', false, -8297501.0, ["0P", "9qrJR0R"]);
INSERT INTO t2 VALUES ('2010-01-04', '2010-01-01 08:00:14', '2010-01-12 08:00:14', '', '', false, '2010-01-28 08:00:14', [-341009656, 1055159341, -587660898, -48127332, 1055159341, -281109590], 0.0003, false, 0.9516504271, [-309083208, 635352577, -309083208, -1815155963, -281109590, -772861656, -1671438228]), ('2010-01-20', '2010-01-07 08:00:14', '2010-01-28 08:00:14', '', '', false, '2010-01-13 08:00:14', [-790335553, 924875669, -146251894, -341009656, 1282886662, 1406085628, 571487567, -1207317514, -790335553, 924875669, 995762018, 995762018, -896198980], 0.0001, true, 0.0623693758, []);
INSERT INTO t1 VALUES ('2010-01-23 08:00:14', '', '2009-12-31 08:00:14', '2010-01-30', 7, true, false, '2010-01-19 08:00:14', 14, false, -73268611, 0.8140842413986894, '2010-01-03 08:00:14', true, 0.38004624807978715, ["tnOCGBlVp", "", "4l", "vNo", "", "8EzZ", "Xh4Hb0qK", "p"]);
INSERT INTO t0 VALUES ('2010-01-19 08:00:14', 'N', '2010-01-11 08:00:14', 'LGo', NULL, 1, 78.5, '2010-01-31', '2010-01-11 08:00:14', hll_hash(''));
INSERT INTO t1 VALUES ('2010-01-13 08:00:14', '9', '2010-01-26 08:00:14', '2010-01-07', 1, true, false, '2010-01-27 08:00:14', 11, false, -772861656, 0.40873386537206924, '2010-01-14 08:00:14', true, 0.9250094078721728, ["UCP", "y1", "i", "aZN9", "", "v", "", "2yCYKTqBc", "M", "DDRhRIm", "sq", "Q2a87"]), ('2010-01-05 08:00:14', '', '2010-01-16 08:00:14', '2010-01-18', 3, false, true, '2010-01-03 08:00:14', 4, false, 1055159341, 0.9250094078721728, '2010-01-06 08:00:14', true, 6.4356245E8, ["", "QjbEX", "p0e", "d3dSh", "e"]);
INSERT INTO t1 VALUES ('2010-01-26 08:00:14', '3s', '2010-01-13 08:00:14', '2010-01-04', 7, false, false, '2010-01-25 08:00:14', 11, true, -48127332, 0.5262373833635497, '2010-01-19 08:00:14', false, 0.5134260916920808, ["s", "OGglt9K", "", "Q", "PeqNKOVE4", "", "aSp", "7t"]), ('2010-01-25 08:00:14', 'llD', '2010-01-16 08:00:14', '2010-01-20', 0, true, false, '2010-01-25 08:00:14', 14, true, 1282886662, -7.90335553E8, '2010-01-19 08:00:14', true, 0.8140842413986894, ["", "KPnAcM4L", "nQajtU7", "cF", "X", "pmO", "IaDw", "6qzCLl", ""]), ('2010-01-05 08:00:14', '', '2010-01-18 08:00:14', '2010-01-11', 1, true, false, '2010-01-06 08:00:14', 6, true, -1251641794, 0.5797383985295895, '2010-01-27 08:00:14', false, 0.6596305525353524, ["e6A", "V5", "ONS", "G", "", "qM"]);
CREATE MATERIALIZED VIEW v0 AS SELECT t1_50.c_1_0, MIN(t1_50.c_1_1) , MIN(t1_50.c_1_2) , MAX(t1_50.c_1_3) , SUM(t1_50.c_1_4) , MIN(t1_50.c_1_5) , MAX(t1_50.c_1_6) , MIN(t1_50.c_1_7) , COUNT(t1_50.c_1_8) , MAX(t1_50.c_1_9) , SUM(t1_50.c_1_10) , SUM(t1_50.c_1_11) , MIN(t1_50.c_1_12) , MAX(t1_50.c_1_13) , SUM(t1_50.c_1_14)  FROM t1 AS t1_50 GROUP BY t1_50.c_1_0 ORDER BY t1_50.c_1_0;
CREATE MATERIALIZED VIEW v0 AS SELECT t2_54.c_2_2, t2_54.c_2_4, t2_54.c_2_6, t2_54.c_2_9, t2_54.c_2_10, MAX(t2_54.c_2_0) , MAX(t2_54.c_2_1) , MIN(t2_54.c_2_3) , MAX(t2_54.c_2_5) , SUM(t2_54.c_2_8)  FROM t2 AS t2_54 GROUP BY t2_54.c_2_2, t2_54.c_2_4, t2_54.c_2_6, t2_54.c_2_9, t2_54.c_2_10 ORDER BY t2_54.c_2_2, t2_54.c_2_4, t2_54.c_2_6 DESC, t2_54.c_2_9, t2_54.c_2_10 ASC;
WITH with_t_0 as (SELECT t1_59.c_1_0, t1_59.c_1_1, t1_59.c_1_2, t1_59.c_1_3, t1_59.c_1_4, t1_59.c_1_5, t1_59.c_1_6, t1_59.c_1_7, t1_59.c_1_8, t1_59.c_1_9, t1_59.c_1_10, t1_59.c_1_11, t1_59.c_1_12, t1_59.c_1_13, t1_59.c_1_14 FROM t1 AS t1_59 WHERE  ( (SELECT t2_60.c_2_0 FROM t0 AS t0_58,  t2 AS t2_60 LEFT ANTI JOIN t1 AS t1_59 ON t2_60.c_2_8 = t1_59.c_1_8 AND t2_60.c_2_8 >= t1_59.c_1_8 AND t2_60.c_2_3 < t1_59.c_1_4 AND t2_60.c_2_3 <= t1_59.c_1_4 AND t2_60.c_2_10 >= t1_59.c_1_3 AND t2_60.c_2_10 > t1_59.c_1_3 AND t2_60.c_2_9 < t1_59.c_1_2 AND t2_60.c_2_9 = t1_59.c_1_2 WHERE  ( CAST(t1_59.c_1_11 AS DATE )  ) = ( CASE  WHEN false THEN t1_59.c_1_12 ELSE t1_59.c_1_12 END ) )  ) < ( (SELECT t0_58.c_0_0 FROM t0 AS t0_58, t1 AS t1_59 WHERE true)  )  ORDER BY t1_59.c_1_0) , with_t_1 as (SELECT t1_59.c_1_0, t1_59.c_1_1, t1_59.c_1_2, t1_59.c_1_3, t1_59.c_1_4, t1_59.c_1_5, t1_59.c_1_6, t1_59.c_1_7, t1_59.c_1_8, t1_59.c_1_9, t1_59.c_1_10, t1_59.c_1_11, t1_59.c_1_12, t1_59.c_1_13, t1_59.c_1_14 FROM t1 AS t1_59 WHERE true) SELECT COUNT(*) FROM t1 AS t1_59, with_t_0 AS with_t_0, with_t_1 AS with_t_1 WHERE (( ( t1_59.c_1_14 ) <= ( t1_59.c_1_14 ) ) IS NULL);

```

```
2022-08-12 15:30:50,181 WARN (starrocks-mysql-nio-pool-18|23446) [StmtExecutor.execute():491] execute Exception, sql WITH with_t_0 as (SELECT t1_59.c_1_0, t1_59.c_1_1, t1_59.c_1_2, t1_59.c_1_3, t1_59.c_1_4, t1_59.c_1_5, t1_59.c_1_6, t1_59.c_1_7, t1_59.c_1_8, t1_59.c_1_9, t1_59.c_1_10, t1_59.c_1_11, t1_59.c_1_12, t1_59.c_1_13, t1_59.c_1_14 FROM t1 AS t1_59 WHERE  ( (SELECT t2_60.c_2_0 FROM t0 AS t0_58,  t2 AS t2_60 LEFT ANTI JOIN t1 AS t1_59 ON t2_60.c_2_8 = t1_59.c_1_8 AND t2_60.c_2_8 >= t1_59.c_1_8 AND t2_60.c_2_3 < t1_59.c_1_4 AND t2_60.c_2_3 <= t1_59.c_1_4 AND t2_60.c_2_10 >= t1_59.c_1_3 AND t2_60.c_2_10 > t1_59.c_1_3 AND t2_60.c_2_9 < t1_59.c_1_2 AND t2_60.c_2_9 = t1_59.c_1_2 WHERE  ( CAST(t1_59.c_1_11 AS DATE )  ) = ( CASE  WHEN false THEN t1_59.c_1_12 ELSE t1_59.c_1_12 END ) )  ) < ( (SELECT t0_58.c_0_0 FROM t0 AS t0_58, t1 AS t1_59 WHERE true)  )  ORDER BY t1_59.c_1_0) , with_t_1 as (SELECT t1_59.c_1_0, t1_59.c_1_1, t1_59.c_1_2, t1_59.c_1_3, t1_59.c_1_4, t1_59.c_1_5, t1_59.c_1_6, t1_59.c_1_7, t1_59.c_1_8, t1_59.c_1_9, t1_59.c_1_10, t1_59.c_1_11, t1_59.c_1_12, t1_59.c_1_13, t1_59.c_1_14 FROM t1 AS t1_59 WHERE true) SELECT COUNT(*) FROM t1 AS t1_59, with_t_0 AS with_t_0, with_t_1 AS with_t_1 WHERE (( ( t1_59.c_1_14 ) <= ( t1_59.c_1_14 ) ) IS NULL)
java.lang.IllegalStateException: null
        at com.google.common.base.Preconditions.checkState(Preconditions.java:494) ~[spark-dpp-1.0.0.jar:?]
        at com.starrocks.sql.optimizer.statistics.Statistics.getColumnStatistic(Statistics.java:56) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.statistics.StatisticsCalculator.computeGroupByStatistics(StatisticsCalculator.java:694) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.statistics.StatisticsCalculator.computeAggregateNode(StatisticsCalculator.java:674) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.statistics.StatisticsCalculator.visitLogicalAggregation(StatisticsCalculator.java:658) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.statistics.StatisticsCalculator.visitLogicalAggregation(StatisticsCalculator.java:137) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.operator.logical.LogicalAggregationOperator.accept(LogicalAggregationOperator.java:132) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.statistics.StatisticsCalculator.estimatorStats(StatisticsCalculator.java:153) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.task.DeriveStatsTask.execute(DeriveStatsTask.java:76) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.task.SeriallyTaskScheduler.executeTasks(SeriallyTaskScheduler.java:42) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.Optimizer.memoOptimize(Optimizer.java:166) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.Optimizer.optimize(Optimizer.java:105) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.StatementPlanner.createQueryPlan(StatementPlanner.java:89) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.StatementPlanner.plan(StatementPlanner.java:54) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.StmtExecutor.execute(StmtExecutor.java:348) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.ConnectProcessor.handleQuery(ConnectProcessor.java:316) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.ConnectProcessor.dispatch(ConnectProcessor.java:429) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.ConnectProcessor.processOnce(ConnectProcessor.java:667) ~[starrocks-fe.jar:?]
        at com.starrocks.mysql.nio.ReadListener.lambda$handleEvent$0(ReadListener.java:55) ~[starrocks-fe.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_272]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_272]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_272]

```

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
 - mysql> select current_version();
+----------------------+
| current_version()    |
+----------------------+
| MAIN-RELEASE e8ba97d |
+----------------------+

**Comment by LiShuMing** [comment] 2022-08-16 12:50
@wanpengfei-git  I cannot reproduce this case in dev env. But I found another problem by using the provided sqls.

cannot use min(boolean) in Create MV but can use it in select.
![MmOCpOJSMF](https://user-images.githubusercontent.com/5104975/184883393-578bc464-94ed-4072-8003-e1480d26b6de.jpg)

Bug the exception(check) should be ignored by returning Unkown when column statics don't exists

**Comment by LiShuMing** [comment] 2022-08-17 01:52
This has been fixed by https://github.com/StarRocks/starrocks/pull/9946
which throw `UnSupported Exception`.

![image](https://user-images.githubusercontent.com/5104975/185016907-250eb89a-4bae-4127-9943-672783025d45.png)

However the problem above still exists: CREATE MV failed.

**Closed** 2022-08-17 02:38 UTC
Labels: type/bug, sqlancer
