### ISSUE TITLE
[sqlancer] query of left anti join, the size of the result sets mismatch

### ISSUE THREAD

**Issue by dulong41** [StarRocks/starrocks#12949] opened 2022-11-04 01:46 UTC
### Steps to reproduce the behavior (Required)
1. CREATE TABLE '...'
2. INSERT INTO '....'
3. SELECT  '....'

DROP DATABASE IF EXISTS g13;
CREATE DATABASE g13;
USE g13;
admin set frontend config ("enable_decimal_v3" = "true");
CREATE TABLE IF NOT EXISTS t0 (c_0_0 DATETIME NULL ) DUPLICATE KEY (c_0_0) DISTRIBUTED BY HASH (c_0_0) BUCKETS 3 properties("replication_num"="3") ;
CREATE TABLE t1 (c_1_0 DATE NULL ,c_1_1 DATETIME NOT NULL ,c_1_2 CHAR(21) NOT NULL ,c_1_3 DOUBLE NOT NULL ,c_1_4 BIGINT NULL ,c_1_5 INT NOT NULL ,c_1_6 ARRAY<INT> NOT NULL ,c_1_7 DATETIME NOT NULL ) DUPLICATE KEY (c_1_0,c_1_1) PARTITION BY RANGE(c_1_1) (START ("2010-01-01") END ("2022-12-31") EVERY (INTERVAL 113 day)) DISTRIBUTED BY HASH (c_1_1) BUCKETS 3 properties("replication_num"="3") ;
CREATE TABLE t2 (c_2_0 DATETIME NOT NULL ,c_2_1 VARCHAR(21) NOT NULL ,c_2_2 CHAR(11) NULL ,c_2_3 BOOLEAN NULL ,c_2_4 LARGEINT NULL ,c_2_5 VARCHAR(1) NOT NULL ,c_2_6 DATETIME NULL ,c_2_7 LARGEINT NOT NULL ,c_2_8 BIGINT NULL ,c_2_9 DECIMAL(11, 4)  NULL ,c_2_10 LARGEINT NOT NULL ,c_2_11 VARCHAR(11) NULL ,c_2_12 DECIMAL(14, 10)  NULL ,c_2_13 DATE NOT NULL ,c_2_14 DATETIME NOT NULL ,c_2_15 DOUBLE NULL , INDEX index1_c_2_7(`c_2_7`) USING BITMAP) DUPLICATE KEY (c_2_0,c_2_1,c_2_2,c_2_3,c_2_4,c_2_5,c_2_6,c_2_7,c_2_8,c_2_9,c_2_10,c_2_11,c_2_12,c_2_13,c_2_14) PARTITION BY RANGE(c_2_0) (START ("2010-01-01") END ("2022-12-31") EVERY (INTERVAL 98 day)) DISTRIBUTED BY HASH (c_2_3,c_2_10,c_2_13,c_2_7,c_2_0,c_2_14,c_2_1,c_2_8,c_2_6,c_2_11,c_2_9,c_2_5) BUCKETS 3 properties("replication_num"="3") ;
CREATE TABLE IF NOT EXISTS t3 (c_3_0 LARGEINT NOT NULL,c_3_1 DECIMAL(9, 7)  NOT NULL,c_3_2 DATETIME NOT NULL,c_3_3 ARRAY<STRING> NOT NULL,c_3_4 DOUBLE NOT NULL,c_3_5 BOOLEAN NOT NULL,c_3_6 ARRAY<INT> NOT NULL, INDEX index1_c_3_2(`c_3_2`) USING BITMAP) PRIMARY KEY (c_3_0) DISTRIBUTED BY HASH (c_3_0) BUCKETS 3 properties("replication_num"="3") ;
INSERT INTO t1 VALUES ('2010-01-09', '2010-01-10 08:00:14', 'QWQo', 0.01539204947355266, 1595904409, 1, [1414504228, 1595904409, 1595904409, 1595904409, 515402088, 1595904409, 515402088, 1414504228, 219689816, 219689816], '2010-01-26 08:00:14'), ('2010-01-06', '2010-01-30 08:00:14', 'S', 0.01539204947355266, -1494288593, 3, [-1619518200, 700165012, -1577855392, 55662069, -1309999504, 1567235442, -1756740774, 515402088, 360703978], '2010-01-22 08:00:14'), ('2010-01-31', '2010-01-31 08:00:14', 'FVsxZJA', 0.7119630928140968, -834943509, 1, [-1577855392, 1414504228, -1494288593, 846859632, 243944900, 700165012], '2010-01-02 08:00:14');
INSERT INTO t2 VALUES ('2010-01-29 08:00:14', 'mXnu', 'QUj', true, -1619518200, '', '2010-01-10 08:00:14', -622242691, -403758750, 995.4059, -592032283, '', 1.081E-7, '2010-01-25', '2010-01-02 08:00:14', 0.5407381432113652), ('2010-01-18 08:00:14', 'IP', 'zOl', true, -1342469920, '', '2010-01-29 08:00:14', 1306442264, -658326275, 725.0141, 1114836479, '', 3.59E-8, '2010-01-29', '2010-01-09 08:00:14', NULL);
INSERT INTO t0 VALUES ('2010-01-01 08:00:14');
INSERT INTO t0 VALUES (NULL), ('2010-01-26 08:00:14'), ('2010-01-06 08:00:14');
INSERT INTO t3 VALUES (-622242691, 0.0000074, '2009-12-31 08:00:14', ["p", "9QwP", "PT59f", "X"], 0.1758216740482681, true, [1073164906, -1263662020, 1414504228, 219689816, -1872440304, -622242691, 485842627, -422885457]);
INSERT INTO t0 VALUES ('2010-01-06 08:00:14'), ('2010-01-13 08:00:14');
INSERT INTO t0 VALUES ('2010-01-23 08:00:14'), (NULL);
INSERT INTO t2 VALUES ('2010-01-05 08:00:14', '', '', NULL, 1443993521, '', NULL, 2130494444, -1921810064, 152.6924, 846859632, '9H', 6.441E-7, '2010-01-10', '2010-01-01 08:00:14', 0.48864846524606853), ('2010-01-11 08:00:14', '6iHVPY', 'S', true, -422885457, '', '2010-01-09 08:00:14', 1150162027, 722347836, NULL, 0, 'tHAgJ0', 9.71E-8, '2010-01-18', '2010-01-02 08:00:14', 0.14898591301573683);
INSERT INTO t3 VALUES (-504348260, 0.0000053, '2010-01-11 08:00:14', ["", "42", "2xsttBBpJ", "H", "QNCG6UQ", "jdzFc6j", "4b", "", "09imrMc0I", "ab", ""], 0.16747594811173294, true, [-122296482, 1150162027, 1713360931, -504348260, -2140427150, 846859632, 88793864, -622242691, -1953940025, 883951177, -1342469920, -448472712, 1834013098]), (-592032283, 0.0000034, '2010-01-15 08:00:14', ["b", "vkYWGiojQ", "JEa", "", "t"], 0.4380042380073814, true, [-1756740774, 881191354, -184869532, -592032283, -355579144, -504348260, 1073164906, -394657245, 1269548527, -658326275, -834943509]);
INSERT INTO t0 VALUES ('2010-01-08 08:00:14'), ('2010-01-19 08:00:14');
INSERT INTO t0 VALUES ('2010-01-21 08:00:14'), ('2010-01-13 08:00:14'), ('2010-01-24 08:00:14');
CREATE VIEW v0 AS SELECT DISTINCT t0_195.c_0_0, t2_197.c_2_0, t2_197.c_2_1, t2_197.c_2_2, t2_197.c_2_3, t2_197.c_2_4, t2_197.c_2_5, t2_197.c_2_6, t2_197.c_2_7, t2_197.c_2_8, t2_197.c_2_9, t2_197.c_2_10, t2_197.c_2_11, t2_197.c_2_12, t2_197.c_2_13, t2_197.c_2_14, t2_197.c_2_15 FROM t0 AS t0_195, t2 AS t2_197 WHERE (NOT (false)) GROUP BY t0_195.c_0_0, t2_197.c_2_0, t2_197.c_2_1, t2_197.c_2_2, t2_197.c_2_3, t2_197.c_2_4, t2_197.c_2_5, t2_197.c_2_6, t2_197.c_2_7, t2_197.c_2_8, t2_197.c_2_9, t2_197.c_2_10, t2_197.c_2_11, t2_197.c_2_12, t2_197.c_2_13, t2_197.c_2_14, t2_197.c_2_15 ORDER BY t2_197.c_2_1, t2_197.c_2_11, t2_197.c_2_9, t2_197.c_2_3, t2_197.c_2_14, t2_197.c_2_3, t2_197.c_2_10, t2_197.c_2_3, t2_197.c_2_8, t2_197.c_2_15;
CREATE MATERIALIZED VIEW v0 AS SELECT t2_201.c_2_0, t2_201.c_2_1, t2_201.c_2_2, t2_201.c_2_3, t2_201.c_2_4, t2_201.c_2_5, t2_201.c_2_6, t2_201.c_2_7, t2_201.c_2_8, t2_201.c_2_9, t2_201.c_2_10, t2_201.c_2_11, t2_201.c_2_12, t2_201.c_2_13, t2_201.c_2_14, t2_201.c_2_15 FROM t2 AS t2_201;
INSERT INTO t3 VALUES (-837047383, 0.0000058, '2010-01-04 08:00:14', ["SAB", "G1MiUxM", "", "aCc", "Ao", "cP", "QF4a3VXq", ""], -1.7976931348623157E308, true, [-592032283, -1982944453, -151986792, 844068984]);
INSERT INTO t1 VALUES ('2010-01-02', '2010-01-09 08:00:14', '', 0.6291956040853983, -1124522408, 30, [1073164906, -1476425670, 1961859033, -1546479958], '2010-01-10 08:00:14'), ('2010-01-31', '2010-01-05 08:00:14', '', 0.46694521307651893, -732229784, 26, [515402088, -1881819352, -1982944453, -1476425670, -658326275, 1141584402, 2135654758, 258239788, -1884095539, 970070181, -2005333307, 470029300, 1713360931, 219689816], '2010-01-21 08:00:14'), (NULL, '2010-01-22 08:00:14', 'AE2Paaid', -4.22885457E8, -1577855392, 7, [-551459873, -108624598, -1342469920, 242683251, -1531018806, 699871095, -1378900640, -834943509, -1288011042, -1263662020], '2010-01-19 08:00:14');
INSERT INTO t3 VALUES (722347836, 0.0000055, '2010-01-20 08:00:14', [""], 0.4380042380073814, false, [-1982944453, -1124522408, -673324995, -1476425670, -2086901309, 1005896432, 1662256577]), (1713360931, 0.0000078, '2010-01-10 08:00:14', ["3pkp", "W", "dfuT8", "N8", "0x3Wp", "u"], 2.42683251E8, false, [881191354, 298737527, -547978157, -526237108, 2039052405, 17059503, 1662256577, -16284633, -1921810064, -547978157, -1751963674, 1809869922]);
INSERT INTO t2 VALUES ('2010-01-22 08:00:14', '', NULL, false, 376216393, '', NULL, -422885457, 2039052405, 495.0809, -547978157, 'ib0', 4.905E-7, '2010-01-28', '2010-01-01 08:00:14', -1.872440304E9), ('2010-01-09 08:00:14', 'F', '7', true, -200732091, '', '2010-01-12 08:00:14', -448472712, -425649424, 827.8903, 1809869922, '', 5.965E-7, '2010-01-20', '2010-01-27 08:00:14', 0.2760031567990665);
INSERT INTO t3 VALUES (-122296482, 0.0000032, '2010-01-19 08:00:14', ["7", "", "DNH9D", "", "m"], 0.9545622946131205, false, [636134686, -1948471477, -403758750, 3890650, 1306442264, 485842627, -1779996628, 812872335, 1529249512, 1306442264, -1921810064, -403758750, 626085498]), (844068984, 9E-7, '2010-01-25 08:00:14', ["J", "Im5h", "qnu0N7Hv", "8Kl", "qhL", "Ub"], 0.8739258695608947, false, [-431674409, -834943509, 1597124469, 3890650, 1026828729, -1115731772, 1679831985, 1340635772, -448472712, -1539137814, -1851693102, 2036587027]);
DELETE FROM t0 WHERE c_0_0='1970-01-09 19:27:31';

---- SELECT t3_210.c_3_0, t3_210.c_3_1, t3_210.c_3_4 FROM  t3 AS t3_210 LEFT ANTI JOIN t1 AS t1_208 ON t3_210.c_3_1 = t1_208.c_1_3 AND t3_210.c_3_1 = t1_208.c_1_3 GROUP BY t3_210.c_3_0, t3_210.c_3_1, t3_210.c_3_4;
---- cardinality: 8
---- SELECT t3_210.c_3_0, t3_210.c_3_1, t3_210.c_3_4 FROM  t3 AS t3_210 LEFT ANTI JOIN t1 AS t1_208 ON t3_210.c_3_1 = t1_208.c_1_3 AND t3_210.c_3_1 = t1_208.c_1_3 WHERE  ( (SELECT t0_207.c_0_0 FROM t0 AS t0_207 WHERE (t3_210.c_3_2) IN ('1970-01-14 11:06:56') )  ) < ( (SELECT t1_208.c_1_0 FROM  t1 AS t1_208 LEFT ANTI JOIN (SELECT t3_210.c_3_0, t3_210.c_3_1, t3_210.c_3_2, t3_210.c_3_4, t3_210.c_3_5 FROM t3 AS t3_210) subt3 ON t1_208.c_1_2 = subt3.c_3_5 AND t1_208.c_1_2 != subt3.c_3_5 AND t1_208.c_1_1 < subt3.c_3_0 AND t1_208.c_1_1 <= subt3.c_3_0 WHERE false)  )  GROUP BY t3_210.c_3_0, t3_210.c_3_1, t3_210.c_3_4 UNION SELECT t3_210.c_3_0, t3_210.c_3_1, t3_210.c_3_4 FROM  t3 AS t3_210 LEFT ANTI JOIN t1 AS t1_208 ON t3_210.c_3_1 = t1_208.c_1_3 AND t3_210.c_3_1 = t1_208.c_1_3 WHERE (NOT ( ( (SELECT t0_207.c_0_0 FROM t0 AS t0_207 WHERE (t3_210.c_3_2) IN ('1970-01-14 11:06:56') )  ) < ( (SELECT t1_208.c_1_0 FROM  t1 AS t1_208 LEFT ANTI JOIN (SELECT t3_210.c_3_0, t3_210.c_3_1, t3_210.c_3_2, t3_210.c_3_4, t3_210.c_3_5 FROM t3 AS t3_210) subt3 ON t1_208.c_1_2 = subt3.c_3_5 AND t1_208.c_1_2 != subt3.c_3_5 AND t1_208.c_1_1 < subt3.c_3_0 AND t1_208.c_1_1 <= subt3.c_3_0 WHERE false)  ) )) GROUP BY t3_210.c_3_0, t3_210.c_3_1, t3_210.c_3_4 UNION SELECT t3_210.c_3_0, t3_210.c_3_1, t3_210.c_3_4 FROM  t3 AS t3_210 LEFT ANTI JOIN t1 AS t1_208 ON t3_210.c_3_1 = t1_208.c_1_3 AND t3_210.c_3_1 = t1_208.c_1_3 WHERE (( ( (SELECT t0_207.c_0_0 FROM t0 AS t0_207 WHERE (t3_210.c_3_2) IN ('1970-01-14 11:06:56') )  ) < ( (SELECT t1_208.c_1_0 FROM  t1 AS t1_208 LEFT ANTI JOIN (SELECT t3_210.c_3_0, t3_210.c_3_1, t3_210.c_3_2, t3_210.c_3_4, t3_210.c_3_5 FROM t3 AS t3_210) subt3 ON t1_208.c_1_2 = subt3.c_3_5 AND t1_208.c_1_2 != subt3.c_3_5 AND t1_208.c_1_1 < subt3.c_3_0 AND t1_208.c_1_1 <= subt3.c_3_0 WHERE false)  ) ) IS NULL) GROUP BY t3_210.c_3_0, t3_210.c_3_1, t3_210.c_3_4;
---- cardinality: 0

### Expected behavior (Required)
-- SELECT t3_210.c_3_0, t3_210.c_3_1, t3_210.c_3_4 FROM  t3 AS t3_210 LEFT ANTI JOIN t1 AS t1_208 ON t3_210.c_3_1 = t1_208.c_1_3 AND t3_210.c_3_1 = t1_208.c_1_3 GROUP BY t3_210.c_3_0, t3_210.c_3_1, t3_210.c_3_4;
-- cardinality: 8

### Real behavior (Required)
-- SELECT t3_210.c_3_0, t3_210.c_3_1, t3_210.c_3_4 FROM  t3 AS t3_210 LEFT ANTI JOIN t1 AS t1_208 ON t3_210.c_3_1 = t1_208.c_1_3 AND t3_210.c_3_1 = t1_208.c_1_3 WHERE  ( (SELECT t0_207.c_0_0 FROM t0 AS t0_207 WHERE (t3_210.c_3_2) IN ('1970-01-14 11:06:56') )  ) < ( (SELECT t1_208.c_1_0 FROM  t1 AS t1_208 LEFT ANTI JOIN (SELECT t3_210.c_3_0, t3_210.c_3_1, t3_210.c_3_2, t3_210.c_3_4, t3_210.c_3_5 FROM t3 AS t3_210) subt3 ON t1_208.c_1_2 = subt3.c_3_5 AND t1_208.c_1_2 != subt3.c_3_5 AND t1_208.c_1_1 < subt3.c_3_0 AND t1_208.c_1_1 <= subt3.c_3_0 WHERE false)  )  GROUP BY t3_210.c_3_0, t3_210.c_3_1, t3_210.c_3_4 UNION SELECT t3_210.c_3_0, t3_210.c_3_1, t3_210.c_3_4 FROM  t3 AS t3_210 LEFT ANTI JOIN t1 AS t1_208 ON t3_210.c_3_1 = t1_208.c_1_3 AND t3_210.c_3_1 = t1_208.c_1_3 WHERE (NOT ( ( (SELECT t0_207.c_0_0 FROM t0 AS t0_207 WHERE (t3_210.c_3_2) IN ('1970-01-14 11:06:56') )  ) < ( (SELECT t1_208.c_1_0 FROM  t1 AS t1_208 LEFT ANTI JOIN (SELECT t3_210.c_3_0, t3_210.c_3_1, t3_210.c_3_2, t3_210.c_3_4, t3_210.c_3_5 FROM t3 AS t3_210) subt3 ON t1_208.c_1_2 = subt3.c_3_5 AND t1_208.c_1_2 != subt3.c_3_5 AND t1_208.c_1_1 < subt3.c_3_0 AND t1_208.c_1_1 <= subt3.c_3_0 WHERE false)  ) )) GROUP BY t3_210.c_3_0, t3_210.c_3_1, t3_210.c_3_4 UNION SELECT t3_210.c_3_0, t3_210.c_3_1, t3_210.c_3_4 FROM  t3 AS t3_210 LEFT ANTI JOIN t1 AS t1_208 ON t3_210.c_3_1 = t1_208.c_1_3 AND t3_210.c_3_1 = t1_208.c_1_3 WHERE (( ( (SELECT t0_207.c_0_0 FROM t0 AS t0_207 WHERE (t3_210.c_3_2) IN ('1970-01-14 11:06:56') )  ) < ( (SELECT t1_208.c_1_0 FROM  t1 AS t1_208 LEFT ANTI JOIN (SELECT t3_210.c_3_0, t3_210.c_3_1, t3_210.c_3_2, t3_210.c_3_4, t3_210.c_3_5 FROM t3 AS t3_210) subt3 ON t1_208.c_1_2 = subt3.c_3_5 AND t1_208.c_1_2 != subt3.c_3_5 AND t1_208.c_1_1 < subt3.c_3_0 AND t1_208.c_1_1 <= subt3.c_3_0 WHERE false)  ) ) IS NULL) GROUP BY t3_210.c_3_0, t3_210.c_3_1, t3_210.c_3_4;
-- cardinality: 0

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
mysql> select current_version()
    -> ;
+----------------------+
| current_version()    |
+----------------------+
| MAIN-RELEASE 6643d40 |
+----------------------+
1 row in set (0.00 sec)

**Comment by packy92** [comment] 2022-11-08 12:51
fixed by [[Feature] implement left semi/anti join for NLJ](https://github.com/StarRocks/starrocks/pull/13019)

The bug is caused by mistakenly pushing left join on condition as runtime filter.

**Closed** 2022-11-08 13:01 UTC
Labels: type/bug
