### ISSUE TITLE
primary key tablet do not support delete statement yet

### ISSUE THREAD

**Issue by smilingmoon** [StarRocks/starrocks#6714] opened 2022-05-31 00:50 UTC
### Steps to reproduce the behavior (Required)
CREATE TABLE users(
		user_id bigint NOT NULL,
		name string  NOT NULL,
		email string  NULL,
		address string  NULL,
		age tinyint  NULL,
		sex tinyint  NULL)  
PRIMARY KEY(user_id)  
DISTRIBUTED BY HASH(user_id) BUCKETS 4 
PROPERTIES ( "replication_num" = "1" );

INSERT INTO users VALUES(1001,'张三','111@qq.com','AAA',17,'0');
INSERT INTO users VALUES(1001,'李四','222@qq.com','BBB',18,'1');
INSERT INTO users VALUES(1002,'aaa','222@qq.com','aaa',18,'0');
INSERT INTO users VALUES(1002,'bbb','222@qq.com','bbb',18,'1');

select * from users;

delete from users where user_id = 1001

### Expected behavior (Required)

Expected  user_id is 1001 deleted

### Real behavior (Required)

delete from users where user_id = 1001
> 1064 - primary key tablet do not support delete statement yet
> 时间: 0.001s

### StarRocks version (Required)
mysql> select current_version();
+-------------------+
| current_version() |
+-------------------+
| 2.2.0 671149f     |
+-------------------+

**Comment by decster** [comment] 2022-05-31 01:22
duplicate of https://github.com/StarRocks/starrocks/issues/4361

**Closed** 2022-05-31 01:34 UTC
Labels: type/bug
