### ISSUE TITLE
"SHOW MATERIALIZED VIEWS" gives inconsistent result

### ISSUE THREAD

**Issue by ftong2020** [StarRocks/starrocks#48649] opened 2024-07-21 16:22 UTC
### Steps to reproduce the behavior (Required)
SHOW MATERIALIZED VIEWS

### Expected behavior (Required)
should output complete information for all MVs

### Real behavior (Required)
multiple fields are missing randomly. Run command multiple time will give random null values.
There are no obvious pattern of it.

below is the result of 3 consecutive run in about one minute.
<img width="1219" alt="Screenshot 2024-07-22 at 00 21 09" src="https://github.com/user-attachments/assets/a2f9339c-31a2-4f3f-8f6f-4c7af1f90fe8">
<img width="1219" alt="Screenshot 2024-07-22 at 00 21 03" src="https://github.com/user-attachments/assets/4f78d133-a379-4b2d-beab-688cdcd286e8">
<img width="1219" alt="Screenshot 2024-07-22 at 00 20 57" src="https://github.com/user-attachments/assets/f61cbc95-ba2c-43c9-941b-e16ebf18c50b">

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
3.3.1

**Comment by LiShuMing** [comment] 2024-08-13 02:25
This should be fixed in 3.3.2 by https://github.com/StarRocks/starrocks/pull/49130/files.
You can check it later.

**Comment by nferrario** [comment] 2024-10-01 08:56
This is still happening on 3.3.2

**Comment by nferrario** [comment] 2024-11-12 14:19
Still happening on 3.3.5

**Comment by LiShuMing** [comment] 2024-12-04 10:27
Let me check it, it may be caused by[ #47742](https://github.com/StarRocks/starrocks/pull/47742)

**Closed** 2024-12-06 09:19 UTC
Labels: type/bug
