### ISSUE TITLE
 StarRocksFE start failed

### ISSUE THREAD

**Issue by 0xqq** [StarRocks/starrocks#29534] opened 2023-08-19 09:04 UTC
### Steps to reproduce the behavior (Required)
 StarRocksFE start failed 

### Expected behavior (Required)
com.starrocks.common.DdlException: failed to load AuthorizationManager!
	at com.starrocks.privilege.AuthorizationMgr.load(AuthorizationMgr.java:1804) ~[starrocks-fe.jar:?]
	at com.starrocks.server.GlobalStateMgr.loadRBACPrivilege(GlobalStateMgr.java:1745) ~[starrocks-fe.jar:?]
	at com.starrocks.server.GlobalStateMgr.loadImage(GlobalStateMgr.java:1596) ~[starrocks-fe.jar:?]
	at com.starrocks.server.GlobalStateMgr.initialize(GlobalStateMgr.java:1082) ~[starrocks-fe.jar:?]
	at com.starrocks.StarRocksFE.start(StarRocksFE.java:133) ~[starrocks-fe.jar:?]
	at com.starrocks.StarRocksFE.main(StarRocksFE.java:84) ~[starrocks-fe.jar:?]
Caused by: com.starrocks.privilege.PrivilegeException: role root is not mutable!
	at com.starrocks.privilege.RolePrivilegeCollectionV2.assertMutable(RolePrivilegeCollectionV2.java:74) ~[starrocks-fe.jar:?]
	at com.starrocks.privilege.RolePrivilegeCollectionV2.grant(RolePrivilegeCollectionV2.java:135) ~[starrocks-fe.jar:?]
	at com.starrocks.privilege.DefaultAuthorizationProvider.upgradePrivilegeCollection(DefaultAuthorizationProvider.java:244) ~[starrocks-fe.jar:?]
	at com.starrocks.privilege.AuthorizationMgr.load(AuthorizationMgr.java:1788) ~[starrocks-fe.jar:?]
	... 5 more
### StarRocks version (Required)
 SR3.1

**Comment by gengjun-git** [comment] 2023-08-21 02:26
Can you show the version detail? Was it caused by upgrading/downgrading the cluster, or just restart?

**Comment by gengjun-git** [comment] 2023-08-21 03:40
fixed by #29556

**Closed** 2023-08-21 07:11 UTC
Labels: type/bug
