### ISSUE TITLE
After upgrading the cluster, modifying the attributes of the table causes asynchronous synchronization between the FEs

### ISSUE THREAD

**Issue by WholeWorld-Timothy** [StarRocks/starrocks#21214] opened 2023-04-09 16:41 UTC
### Steps to reproduce the behavior (Required)
Upgrade the cluster from 2.1.1 to 2.5.3, modify the attributes of the primary key model's tables
ALTER TABLE XXX.XXX
SET (“enable_persistent_index”=“true”);
After the upgrade is completed, only LEADER's' alive 'is true, and everything else is false,
There are a large number of errors in the logs of the three nodes' FE:

2023-04-09 23:47:55,030 ERROR (replayer|82) [BDBJournalCursor.deserializeData():241] fail to read journal entity key=21460997, data=
java.io.IOException: UNKNOWN Operation Type 10005
at com.starrocks.journal.JournalEntity.readFields(JournalEntity.java:766) ~[starrocks-fe.jar:?]
at com.starrocks.journal.bdbje.BDBJournalCursor.deserializeData(BDBJournalCursor.java:236) [starrocks-fe.jar:?]
at com.starrocks.journal.bdbje.BDBJournalCursor.next(BDBJournalCursor.java:280) [starrocks-fe.jar:?]
at com.starrocks.server.GlobalStateMgr.replayJournalInner(GlobalStateMgr.java:1894) [starrocks-fe.jar:?]
at com.starrocks.server.GlobalStateMgr$5.runOneCycle(GlobalStateMgr.java:1759) [starrocks-fe.jar:?]
at com.starrocks.common.util.Daemon.run(Daemon.java:115) [starrocks-fe.jar:?]
at com.starrocks.server.GlobalStateMgr$5.run(GlobalStateMgr.java:1824) [starrocks-fe.jar:?]

ignore_unknown_log_id = true，After setting the parameters, the FE node started smoothly, but the query was:
SELECT * FROM information_schema.tables_config WHERE

– TABLE_SCHEMA = ‘MRTDB’;

TABLE_MODEL = ‘PRIMARY_KEYS’

and PROPERTIES like ‘%“enable_persistent_index”:“false”%’;
LEADER node and Follow node enable_persistent_index attribute is inconsistent.

### Expected behavior (Required)

Same metadata

### Real behavior (Required)

Different metadata

### StarRocks version (Required)
 - 2.5.3

**Comment by blanklin030** [comment] 2023-07-26 06:28
@WholeWorld-Timothy this issue is fixed by pr link [https://github.com/StarRocks/starrocks/pull/19504]
the problem is [java.io.IOException: UNKNOWN Operation Type 10005]

**Closed** 2023-07-31 00:29 UTC
Labels: type/bug
