### ISSUE TITLE
incorrect count distinct value with join

### ISSUE THREAD

**Issue by kaijianding** [StarRocks/starrocks#49854] opened 2024-08-15 10:13 UTC
### Steps to reproduce the behavior (Required)
`pt` is partition key, type is `date`
`spu_id` type is `bigint`

Correct reuslt is:  5651249

```sql
SELECT 
    count(distinct spu_id)
FROM 
    t1 a
WHERE a.pt = '2024-08-08'
	AND a.pt >= '2023-12-16'
+------------------------+
| count(DISTINCT spu_id) |
+------------------------+
|                5651249 |
+------------------------+

SELECT 
    count(distinct spu_id)
FROM 
   t1 a
    cross JOIN (
		SELECT date('2024-08-08') as dim_date1
	) d
where a.pt = d.dim_date1
	AND a.pt >= '2023-12-16'
+------------------------+
| count(DISTINCT spu_id) |
+------------------------+
|                3840110 |
+------------------------+

SELECT 
    count(distinct spu_id)
FROM 
    t1 a
    inner JOIN (
		SELECT date('2024-08-08') as dim_date1
	) d
where a.pt = d.dim_date1
	AND a.pt >= '2023-12-16'
+------------------------+
| count(DISTINCT spu_id) |
+------------------------+
|                3840110 |
+------------------------+
```

### Expected behavior (Required)
the result in consistent

### Real behavior (Required)
Result is incorrect with join

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
3.3

**Comment by packy92** [comment] 2024-08-15 11:37
please provide the explain info of these sqls

**Comment by chenminghua8** [comment] 2024-08-16 04:44
The issue seems to be related to distributed deduplication, but it is not easy to reproduce in a single-machine environment.

**Comment by stdpain** [comment] 2024-09-20 06:15
seems closed by https://github.com/StarRocks/starrocks/pull/51150

**Closed by stdpain** 2024-09-20 06:15 UTC
Labels: type/bug
