### ISSUE TITLE
BE crash when create index

### ISSUE THREAD

**Issue by zhangboya1** [StarRocks/starrocks#4166] opened 2022-03-16 10:20 UTC
### Steps to reproduce the behavior (Required)
1. CREATE INDEX xxx USING BITMAP COMMENT 'balabala';

### Expected behavior (Required)
create index ok

### Real behavior (Required)
BE crash

### StarRocks version (Required)
 - 1.19.0

when alter column array<varchar(255)>, BE crashed. Only when I canceled this operation, BE started OK.

**Comment by sduzh** [comment] 2022-03-16 12:30
@zhangboya1 Thanks for your report, could you provide more details on how to reproduce this problem?  I cannot reproduce this problem by executing the following operations, with the codebase in main branch:

1. 
```
CREATE TABLE `t0` (
  `c0` int(11) NULL COMMENT "",
  INDEX idx (`c0`) USING BITMAP COMMENT 'balabala'
) ENGINE=OLAP
DUPLICATE KEY(`c0`)
COMMENT "OLAP"
DISTRIBUTED BY HASH(`c0`) BUCKETS 1
PROPERTIES (
"replication_num" = "1",
"in_memory" = "false",
"storage_format" = "DEFAULT"
);
``` 
2.
```
insert into t0 values(1),(2),(3);
insert into t0 values(1),(2),(3);
insert into t0 values(1),(2),(3);
insert into t0 values(1),(2),(3);
```
3.
```
CREATE INDEX idx ON t0(c0) USING BITMAP COMMENT '';
```
4.
```
insert into t0 values(4),(5),(6),(NULL);
```

**Comment by sduzh** [comment] 2022-03-23 06:22
@zhangboya1 Hi, can you reproduce this problem with the latest version of StarRocks? This seems to be the same problem with #462, which has been fixed.

**Comment by sduzh** [comment] 2022-03-25 02:01
Hi @zhangboya1, I will close this issue due to its duplication with #462.
Please feel free to open this issue again if you have any new discoveries.

**Closed by sduzh** 2022-03-25 02:01 UTC
Labels: type/bug
