### ISSUE TITLE
[Bug] the error message is missed when refresh materialized view task failed

### ISSUE THREAD

**Issue by ABingHuang** [StarRocks/starrocks#8691] opened 2022-07-14 09:43 UTC
### Steps to reproduce the behavior (Required)
1. create table
CREATE TABLE `lineorder` (
  `lo_orderkey` int(11) NOT NULL COMMENT "",
  `lo_linenumber` int(11) NOT NULL COMMENT "",
  `lo_custkey` int(11) NOT NULL COMMENT "",
  `lo_partkey` int(11) NOT NULL COMMENT "",
  `lo_suppkey` int(11) NOT NULL COMMENT "",
  `lo_orderdate` int(11) NOT NULL COMMENT "",
  `lo_orderpriority` varchar(16) NOT NULL COMMENT "",
  `lo_shippriority` int(11) NOT NULL COMMENT "",
  `lo_quantity` int(11) NOT NULL COMMENT "",
  `lo_extendedprice` int(11) NOT NULL COMMENT "",
  `lo_ordtotalprice` int(11) NOT NULL COMMENT "",
  `lo_discount` int(11) NOT NULL COMMENT "",
  `lo_revenue` int(11) NOT NULL COMMENT "",
  `lo_supplycost` int(11) NOT NULL COMMENT "",
  `lo_tax` int(11) NOT NULL COMMENT "",
  `lo_commitdate` int(11) NOT NULL COMMENT "",
  `lo_shipmode` varchar(11) NOT NULL COMMENT ""
) ENGINE=OLAP
DUPLICATE KEY(`lo_orderkey`)
COMMENT "OLAP"
PARTITION BY RANGE(`lo_orderdate`)
(PARTITION p1 VALUES [("-2147483648"), ("19930101")),
PARTITION p2 VALUES [("19930101"), ("19940101")),
PARTITION p3 VALUES [("19940101"), ("19950101")),
PARTITION p4 VALUES [("19950101"), ("19960101")),
PARTITION p5 VALUES [("19960101"), ("19970101")),
PARTITION p6 VALUES [("19970101"), ("19980101")),
PARTITION p7 VALUES [("19980101"), ("19990101")))
DISTRIBUTED BY HASH(`lo_orderkey`) BUCKETS 48;

CREATE TABLE IF NOT EXISTS `customer` (
  `c_custkey` int(11) NOT NULL COMMENT "",
  `c_name` varchar(26) NOT NULL COMMENT "",
  `c_address` varchar(41) NOT NULL COMMENT "",
  `c_city` varchar(11) NOT NULL COMMENT "",
  `c_nation` varchar(16) NOT NULL COMMENT "",
  `c_region` varchar(13) NOT NULL COMMENT "",
  `c_phone` varchar(16) NOT NULL COMMENT "",
  `c_mktsegment` varchar(11) NOT NULL COMMENT ""
) ENGINE=OLAP
DUPLICATE KEY(`c_custkey`)
COMMENT "OLAP"
DISTRIBUTED BY HASH(`c_custkey`) BUCKETS 12
PROPERTIES (
"replication_num" = "1",
"colocate_with" = "groupa2",
"in_memory" = "false",
"storage_format" = "DEFAULT"
);

CREATE TABLE IF NOT EXISTS `dates` (
  `d_datekey` int(11) NOT NULL COMMENT "",
  `d_date` varchar(20) NOT NULL COMMENT "",
  `d_dayofweek` varchar(10) NOT NULL COMMENT "",
  `d_month` varchar(11) NOT NULL COMMENT "",
  `d_year` int(11) NOT NULL COMMENT "",
  `d_yearmonthnum` int(11) NOT NULL COMMENT "",
  `d_yearmonth` varchar(9) NOT NULL COMMENT "",
  `d_daynuminweek` int(11) NOT NULL COMMENT "",
  `d_daynuminmonth` int(11) NOT NULL COMMENT "",
  `d_daynuminyear` int(11) NOT NULL COMMENT "",
  `d_monthnuminyear` int(11) NOT NULL COMMENT "",
  `d_weeknuminyear` int(11) NOT NULL COMMENT "",
  `d_sellingseason` varchar(14) NOT NULL COMMENT "",
  `d_lastdayinweekfl` int(11) NOT NULL COMMENT "",
  `d_lastdayinmonthfl` int(11) NOT NULL COMMENT "",
  `d_holidayfl` int(11) NOT NULL COMMENT "",
  `d_weekdayfl` int(11) NOT NULL COMMENT ""
) ENGINE=OLAP
DUPLICATE KEY(`d_datekey`)
COMMENT "OLAP"
DISTRIBUTED BY HASH(`d_datekey`) BUCKETS 1;

CREATE TABLE IF NOT EXISTS `supplier` (
  `s_suppkey` int(11) NOT NULL COMMENT "",
  `s_name` varchar(26) NOT NULL COMMENT "",
  `s_address` varchar(26) NOT NULL COMMENT "",
  `s_city` varchar(11) NOT NULL COMMENT "",
  `s_nation` varchar(16) NOT NULL COMMENT "",
  `s_region` varchar(13) NOT NULL COMMENT "",
  `s_phone` varchar(16) NOT NULL COMMENT ""
) ENGINE=OLAP
DUPLICATE KEY(`s_suppkey`)
COMMENT "OLAP"
DISTRIBUTED BY HASH(`s_suppkey`) BUCKETS 12
PROPERTIES (
"replication_num" = "1",
"colocate_with" = "groupa4",
"in_memory" = "false",
"storage_format" = "DEFAULT"
);

CREATE TABLE IF NOT EXISTS `part` (
  `p_partkey` int(11) NOT NULL COMMENT "",
  `p_name` varchar(23) NOT NULL COMMENT "",
  `p_mfgr` varchar(7) NOT NULL COMMENT "",
  `p_category` varchar(8) NOT NULL COMMENT "",
  `p_brand` varchar(10) NOT NULL COMMENT "",
  `p_color` varchar(12) NOT NULL COMMENT "",
  `p_type` varchar(26) NOT NULL COMMENT "",
  `p_size` int(11) NOT NULL COMMENT "",
  `p_container` varchar(11) NOT NULL COMMENT ""
) ENGINE=OLAP
DUPLICATE KEY(`p_partkey`)
COMMENT "OLAP"
DISTRIBUTED BY HASH(`p_partkey`) BUCKETS 12
PROPERTIES (
"replication_num" = "1",
"colocate_with" = "groupa5",
"in_memory" = "false",
"storage_format" = "DEFAULT"
);
2. load 100g ssb data
3. create materialized view
create materialized view flat_lineorder
distributed by hash(`LO_ORDERKEY`) buckets 10
REFRESH MANUAL
AS
SELECT `LO_ORDERKEY`, 
`LO_ORDERDATE` , 
`LO_LINENUMBER`, 
`LO_CUSTKEY` , 
`LO_PARTKEY` , 
`LO_SUPPKEY` , 
`LO_ORDERPRIORITY` , 
`LO_SHIPPRIORITY` , 
`LO_QUANTITY` , 
`LO_EXTENDEDPRICE` , 
`LO_ORDTOTALPRICE` , 
`LO_DISCOUNT` ,
`LO_REVENUE` , 
`LO_SUPPLYCOST` , 
`LO_TAX` , 
`LO_COMMITDATE` , 
`LO_SHIPMODE` , 
`C_NAME` , 
`C_ADDRESS` , 
`C_CITY` , 
`C_NATION` , 
`C_REGION` , 
`C_PHONE` , 
`C_MKTSEGMENT` , 
`S_NAME` , 
`S_ADDRESS` , 
`S_CITY` , 
`S_NATION` , 
`S_REGION` , 
`S_PHONE` , 
`P_NAME` , 
`P_MFGR` , 
`P_CATEGORY` , 
`P_BRAND` , 
`P_COLOR` , 
`P_TYPE` , 
`P_SIZE` , 
`P_CONTAINER` 
FROM lineorder l INNER JOIN customer c ON (c.C_CUSTKEY = l.LO_CUSTKEY)  
INNER JOIN supplier s ON (s.S_SUPPKEY = l.LO_SUPPKEY)  
INNER JOIN part p ON  (p.P_PARTKEY = l.LO_PARTKEY);

4. refresh materialized view

refresh materialized view flat_lineorder;

### Expected behavior (Required)
select * from information_schema.task_runs;
the result should contain the error message of failure.

### Real behavior (Required)
the task failed, but the error message is NULL
![U3UzdIneLb](https://user-images.githubusercontent.com/101158374/178953111-55a3c676-14f0-4a21-b7a1-cc021bef0590.jpg)

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`

**Comment by smartlxh** [comment] 2022-07-15 07:12
please assign this to me

**Comment by smartlxh** [comment] 2022-07-19 06:42
@ABingHuang  when i run the sql of creating mv reports a error

![image](https://user-images.githubusercontent.com/13373748/179683138-1ae4f29a-279d-4162-9725-97b097b2f775.png)

**Comment by ABingHuang** [comment] 2022-07-19 07:13
@smartlxh which version is your code? is it master?

**Comment by smartlxh** [comment] 2022-07-19 07:30
> @smartlxh which version is your code? is it master?

yeap, it's master.

**Comment by smartlxh** [comment] 2022-07-19 10:42
that'ok for the error, the reason is that the switch(enable_experimental_mv) in fe config for new mv is not set. But i can't reproduce this bug with the latest code
![image](https://user-images.githubusercontent.com/13373748/179731986-b481e128-2a01-4b74-a2e6-aec252411a50.png)

**Closed** 2022-07-20 01:57 UTC
Labels: type/bug, sig/materialized view
